### PR TITLE
replaced deprecated color muted with secondary

### PR DESCRIPTION
**Pull request by PanderMusubi**
See https://getbootstrap.com/docs/5.3/customize/color/ and https://getbootstrap.com/docs/5.3/migration/#utilities-2

### CODE REVIEW

**Comment by PanderMusubi** [comment]
@greyli also refactor the usage of `text-muted` for Bootstrap 4 in `flask_bootstrap/template/bootstrap4/form.html` or leave that as is?

**Comment by greyli** [comment]
Which was the first version of the `text-body-secondary` to be introduced?

**Comment by PanderMusubi** [comment]
> Which was the first version of the `text-body-secondary` to be introduced?

I have no idea. Tried to find it. I think at least 5.2.

**Comment by greyli** [comment]
Merged, thanks!

**Pull request merged**
