### PR TITLE
upgrade bootstrap 5.3.0

### PR DESCRIPTION
**Pull request by PanderMusubi**

### CODE REVIEW

**Review by greyli — CHANGES_REQUESTED** [review]
The default CDN version and integrity values should be updated as well. https://github.com/helloflask/bootstrap-flask/blob/master/flask_bootstrap/__init__.py#L262-L266

**Comment by PanderMusubi** [comment]
> The default CDN version and integrity values should be updated as well. https://github.com/helloflask/bootstrap-flask/blob/master/flask_bootstrap/__init__.py#L262-L266

Thanks. Will do later today.

**Comment by PanderMusubi** [comment]
Done, also updated https://github.com/helloflask/bootstrap-flask/discussions/300

**Comment by PanderMusubi** [comment]
@greyli I see there is also an upgrade of popper from 2.11.6 to 2.11.8. Add that also to this PR?

**Comment by greyli** [comment]
> I also see Bootswatch is at 5.3.0 now. I will upgrade that and popper this week and hope we can release soon after that if is okay with you?

LGTM.

**Review by greyli — APPROVED** [review]

**Comment by greyli** [comment]
Merged. I will upgrade Popper and then release 2.3.0.

**Pull request merged**
